server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product_db
    username: rouf
    password: asdqwe123
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update